[master]
masternode ansible_host=172.16.254.4 ansible_user=letris

[workers]
workernode1 ansible_host=172.16.254.2 ansible_user=letris
workernode2 ansible_host=172.16.254.251 ansible_user=letris
workernode3 ansible_host=172.16.254.250 ansible_user=letris