---
# Install and configure containerd

- name: Add Docker apt-key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker-apt-keyring.asc
    mode: "0644"
    force: true

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }} signed-by=/etc/apt/keyrings/docker-apt-keyring.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install containerd
  apt:
    name: containerd.io
    state: present

- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd configuration
  shell: /usr/bin/containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Configure systemd cgroup driver for containerd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: "            SystemdCgroup = false"
    line: "            SystemdCgroup = true"

- name: Enable and restart containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes
